---
remotes:
  vendor: https://github.com/destructuring/definition-basebox
  primary: git@github.com:destructuring/definition-osx
  secondary: git@destructuring.org:destructuring/definition-osx
  sh: https://github.com/destructuring/jason
