--- 
repository: https://github.com/destructuring/definition-osx
application: osx

user: nobody
group: nobody

ruby_loader: /usr/local/rvm/bin/rvm-exec
deploy_ruby: default
app_ruby: default

branches: [ master ]
branch_regex: /

chef_path: .

notify:
  nothing:
